import { Livro } from "./livro";

export const LIVROS: Livro[] = [
        {nome: "Gênesis",               sigla: "Gen"},
        {nome: "Êxodo",                 sigla: "Exod"},
        {nome: "Levítico",              sigla: "Lev"},
        {nome: "Números",               sigla: "Num"},
        {nome: "Deuteronômio",          sigla: "Deut"},
        {nome: "Josué",                 sigla: "Josh"},
        {nome: "Juízes",                sigla: "Judg"},
        {nome: "Rute",                  sigla: "Ruth"},
        {nome: "1 Samuel",              sigla: "1Sam"},
        {nome: "2 Samuel",              sigla: "2Sam"},
        {nome: "1 Reis",                sigla: "1Kgs"},
        {nome: "2 Reis",                sigla: "2Kgs"},
        {nome: "1 Crônicas",            sigla: "1Chr"},
        {nome: "2 Crônicas",            sigla: "2Chr"},
        {nome: "Esdras",                sigla: "Ezra"},
        {nome: "Neemias",               sigla: "Neh"},
        {nome: "Ester",                 sigla: "Esth"},
        {nome: "Jó",                    sigla: "Job"},
        {nome: "Salmos",                sigla: "Ps"},
        {nome: "Provérbios",            sigla: "Prov"},
        {nome: "Eclesiastes",           sigla: "Eccl"},
        {nome: "Canticos",              sigla: "Song"},
        {nome: "Isaías",                sigla: "Isa"},
        {nome: "Jeremias",              sigla: "Jer"},
        {nome: "Lamentações",           sigla: "Lam"},
        {nome: "Ezequiel",              sigla: "Ezek"},
        {nome: "Daniel",                sigla: "Dan"},
        {nome: "Oseias",                sigla: "Hos"},
        {nome: "Joel",                  sigla: "Joel"},
        {nome: "Amós",                  sigla: "Amos"},
        {nome: "Obadias",               sigla: "Obad"},
        {nome: "Jonas",                 sigla: "Jonah"},
        {nome: "Miqueias",              sigla: "Mic"},
        {nome: "Naum",                  sigla: "Nah"},
        {nome: "Habacuque",             sigla: "Hab"},
        {nome: "Sofonias",              sigla: "Zeph"},
        {nome: "Ageu",                  sigla: "Hag"},
        {nome: "Zacarias",              sigla: "Zech"},
        {nome: "Malaquias",             sigla: "Mal"},
        {nome: "Mateus",                sigla: "Matt"},
        {nome: "Marcos",                sigla: "Mark"},
        {nome: "Lucas",                 sigla: "Luke"},
        {nome: "João",                  sigla: "Jonh"},
        {nome: "Atos",                  sigla: "Acts"},
        {nome: "Romanos",               sigla: "Rom"},
        {nome: "1 Coríntios",           sigla: "1Cor"},
        {nome: "2 Coríntios",           sigla: "2Cor"},
        {nome: "Gálatas",               sigla: "Gal"},
        {nome: "Efésios",               sigla: "Eph"},
        {nome: "Filipenses",            sigla: "Phil"},
        {nome: "Colossenses",           sigla: "Col"},
        {nome: "1 Tessalonicenses",     sigla: "1Thess"},
        {nome: "2 Tessalonicenses",     sigla: "2Thess"},
        {nome: "1 Timóteo",             sigla: "1Tim"},
        {nome: "2 Timóteo",             sigla: "2Tim"},
        {nome: "Tito",                  sigla: "Titus"},
        {nome: "Filemom",               sigla: "Phlm"},
        {nome: "Hebreus",               sigla: "Heb"},
        {nome: "Tiago",                 sigla: "Jas"},
        {nome: "1 Pedro",               sigla: "1Pet"},
        {nome: "2 Pedro",               sigla: "2Pet"},
        {nome: "1 João",                sigla: "1John"},
        {nome: "2 João",                sigla: "2John"},
        {nome: "3 João",                sigla: "3John"},
        {nome: "Judas",                 sigla: "Jude"},
        {nome: "Apocalipse",            sigla: "Rev"}

];